name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"
          
      - name: Build and test with Maven
        run: mvn clean test

      - name: Delete previous package versions
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/UcllSoftwareEngineering2425/packages/maven/be.ucll.se.bcs17.courses-backend

      - name: Build and publish to GitHub Packages
        run: |
          mvn --batch-mode deploy
          echo "Verifying package was published successfully..."
          METADATA_URL="https://maven.pkg.github.com/UcllSoftwareEngineering2425/backend-bcs17/be/ucll/se/bcs17/courses-backend/0.0.1-SNAPSHOT/maven-metadata.xml"
          METADATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$METADATA_URL")
          if [[ -z "$METADATA" ]]; then
            echo "❌ Error: Failed to publish package - metadata.xml not found."
            exit 1
          fi
          echo "✅ Package published successfully!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}